version: "3.8"
services:
    mongodb:
        image: "mongo"
        restart: "always"
        networks:
            - sigma_net
        volumes:
            - data:/data/db
            # - ./Backend/data/:/data/db
        ports:
            - "27107:27107"
        # environment:
        # MONGO_INITDB_ROOT_USERNAME: Sigma
        # MONGO_INITDB_ROOT_PASSWORD: Experi2ma
    mongo-express:
        image: mongo-express
        restart: always
        networks:
            - sigma_net
        ports:
            - 8081:8081
        environment:
            # ME_CONFIG_MONGODB_ADMINUSERNAME: Sigma
            # ME_CONFIG_MONGODB_ADMINPASSWORD: Experi2ma
            ME_CONFIG_MONGODB_SERVER: mongodb
            # ME_CONFIG_MONGODB_URL: mongodb://Sigma:Experioma@mongo:27017/
    backend:
        build: "./Sigma_API"
        ports:
            - "5000:5000"
        restart: always
        networks:
            - sigma_net
        volumes:
            - logs:/app/logs
            - /app/node_modules
        stdin_open: true
        tty: true
        depends_on:
            - mongodb
    frontend:
        build: "./Sigma_Solutions"
        ports:
            - "3000:3000"
        restart: always
        networks:
            - sigma_net
        stdin_open: true
        tty: true
        depends_on:
            - backend
networks:
    sigma_net:
        # external: true
        # name: sigma_net
volumes:
    data:
    logs:
        # external: true
        # name: storage
